config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w(Chinese Italian Japanese French Belgian) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
  validates :content, :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]
  def new
    @review = Review.new
  end
  def show

  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Outfit&family=Roboto:wght@300&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @restaurants.each do |restaurant| %>
      <div class="col">
          <div class="card h-100">
              <%= image_tag "https://source.unsplash.com/featured/?restaurant&#{rand(1..5)}", class: "card-img-top" %>
              <div class="card-body">
                <h2 class="card-title"><%restaurant.name %></h2>
                <h4 class="card-text"><%= restaurant.category.split(' ').map(&:titleize).join(' ') %></h4>
                <p class="card-text"><%= restaurant.address %></p>
                <p class="card-text"><%= restaurant.phone_number %></p>
                <%= link_to "See details", restaurant_path(restaurant), class: "btn btn-primary"%>
              </div>
          </div>
      </div>
    <% end %>
  </div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Create new Restaurant</h1>

  <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :category %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.submit class: "btn btn-primary"%>
  <% end %>

</div>

app/views/restaurants/show.html.erb
<div class="container">
<div class="row row-cols-1 row-cols-md-3 g-4 mb-3">
  <div class="col">
    <div class="card h-100">
        <%= image_tag "https://source.unsplash.com/featured/?restaurant&#{rand(1..5)}", class: "card-img-top div.embed-responsive" %>
        <div class="card-body">
          <h2 class="card-title"><%= @restaurant.name %></h2>
          <h4 class="card-text"><%= @restaurant.category.split(' ').map(&:titleize).join(' ')%></h4>
          <p class="card-text"><%= @restaurant.address %></p>
          <p class="card-text"><%= @restaurant.phone_number %></p>
          <%= link_to "See details", restaurant_path(@restaurant), class: "btn btn-primary"%>
        </div>
    </div>
  </div>
</div>

<div class="d-grid gap-2 col-4 mb-3">
  <%= link_to "Add Review",  new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
  <%= link_to "Back To Restaurants", restaurants_path, class: "btn btn-primary "%>
</div>
<%# <div class="row row-cols-1 row-cols-md-3 m-2">
</div> %>
<h4 class="m-3"><strong>Reviews</strong></h4>
<div class="row row-cols-1 row-cols-md-3 m-2">
  <ul class="list-group left-corner">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item">
        <div><%= review.rating %>
        <%= review.content %>
        <%= link_to review_path(review),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %></div>
      <div><i class="fa-solid fa-trash"></i></div>
      <% end %>
      </li>

    <% end %>
  </ul>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1 class="text-center mt-5">Add Review</h1>

  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :rating %>
    <%= f.input :content %>
    <%= f.submit class: "btn btn-primary"%>
  <% end %>

</div>